"""update time and course table

Revision ID: 07aae37a9073
Revises: e9b34e3fd586
Create Date: 2025-11-10 09:39:16.674543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07aae37a9073'
down_revision = 'e9b34e3fd586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('period_end'))
        batch_op.drop_index(batch_op.f('period_id'))
        batch_op.drop_index(batch_op.f('period_start'))

    op.drop_table('periods')
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['time_id'])
        batch_op.create_unique_constraint(None, ['end_time'])
        batch_op.create_unique_constraint(None, ['start_time'])

    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('timetable_ibfk_3'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'staffs', ['staff_id'], ['id'], ondelete='cascade')
        batch_op.drop_column('major_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('timetable_ibfk_3'), 'majors', ['major_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('staff_id')

    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    op.create_table('periods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('period_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('period_start', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('period_end', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('period_start'), ['period_start'], unique=True)
        batch_op.create_index(batch_op.f('period_id'), ['period_id'], unique=True)
        batch_op.create_index(batch_op.f('period_end'), ['period_end'], unique=True)

    # ### end Alembic commands ###
