"""empty message

Revision ID: 0a9f77c71987
Revises: fbe8d34d84a0
Create Date: 2026-05-15 12:04:28.271616

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0a9f77c71987'
down_revision = 'fbe8d34d84a0'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)

    def refresh():
        inspector.clear_cache()

    def has_table(table_name):
        refresh()
        return inspector.has_table(table_name)

    def has_column(table_name, column_name):
        if not has_table(table_name):
            return False
        return column_name in {column["name"] for column in inspector.get_columns(table_name)}

    def drop_foreign_keys(table_name, column_names=None):
        if not has_table(table_name):
            return

        column_names = set(column_names or [])
        for foreign_key in inspector.get_foreign_keys(table_name):
            constrained_columns = set(foreign_key.get("constrained_columns") or [])
            if column_names and not constrained_columns.intersection(column_names):
                continue
            if foreign_key.get("name"):
                op.drop_constraint(foreign_key["name"], table_name, type_="foreignkey")
        refresh()

    def drop_column_if_exists(table_name, column_name):
        if has_column(table_name, column_name):
            drop_foreign_keys(table_name, [column_name])
            with op.batch_alter_table(table_name, schema=None) as batch_op:
                batch_op.drop_column(column_name)
            refresh()

    def drop_table_if_exists(table_name):
        if has_table(table_name):
            op.drop_table(table_name)
            refresh()

    old_tables = [
        "timetables",
        "texts",
        "labels",
        "sections",
        "students",
        "rooms",
        "staffs",
        "days",
        "periods",
        "buildings",
        "roomtypes",
        "roles",
        "ranks",
        "stafftypes",
        "attendances",
        "majors",
        "pages",
    ]

    op.execute("SET FOREIGN_KEY_CHECKS=0")
    try:
        drop_column_if_exists("courses", "staff_id")
        drop_column_if_exists("medias", "section_id")

        if has_table("subjects"):
            if not has_column("subjects", "department_id"):
                with op.batch_alter_table("subjects", schema=None) as batch_op:
                    batch_op.add_column(sa.Column("department_id", sa.Integer(), nullable=True))
                refresh()

                first_department_id = bind.execute(
                    sa.text("SELECT id FROM departments ORDER BY id LIMIT 1")
                ).scalar()
                if first_department_id is not None:
                    bind.execute(
                        sa.text(
                            "UPDATE subjects SET department_id = :department_id "
                            "WHERE department_id IS NULL"
                        ),
                        {"department_id": first_department_id},
                    )

            drop_foreign_keys("subjects", ["major_id"])
            drop_column_if_exists("subjects", "major_id")

            if has_column("subjects", "department_id"):
                with op.batch_alter_table("subjects", schema=None) as batch_op:
                    batch_op.alter_column(
                        "department_id",
                        existing_type=sa.Integer(),
                        nullable=False,
                    )
                    batch_op.create_foreign_key(
                        "fk_subjects_department_id_departments",
                        "departments",
                        ["department_id"],
                        ["id"],
                        ondelete="CASCADE",
                    )

        for table_name in old_tables:
            drop_table_if_exists(table_name)
    finally:
        op.execute("SET FOREIGN_KEY_CHECKS=1")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('subjects_ibfk_1'), 'majors', ['major_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('department_id')

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('medias_ibfk_1'), 'sections', ['section_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('courses_ibfk_5'), 'staffs', ['staff_id'], ['id'], ondelete='CASCADE')

    op.create_table('periods',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('period_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('period_start', mysql.TIME(), nullable=False),
    sa.Column('period_end', mysql.TIME(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('period_start'), ['period_start'], unique=True)
        batch_op.create_index(batch_op.f('period_id'), ['period_id'], unique=True)
        batch_op.create_index(batch_op.f('period_end'), ['period_end'], unique=True)

    op.create_table('attendances',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('attendance_id', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('attendance_id'), ['attendance_id'], unique=True)

    op.create_table('stafftypes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('stype_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('stype_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stafftypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('stype_name'), ['stype_name'], unique=True)
        batch_op.create_index(batch_op.f('stype_id'), ['stype_id'], unique=True)

    op.create_table('texts',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('subject_code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('subject_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('is_cs', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_ct', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('texts_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('roomtypes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('roomtype_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('roomtype_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('roomtypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('roomtype_name'), ['roomtype_name'], unique=True)
        batch_op.create_index(batch_op.f('roomtype_id'), ['roomtype_id'], unique=True)

    op.create_table('buildings',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('building_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('building_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('buildings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('building_name'), ['building_name'], unique=True)
        batch_op.create_index(batch_op.f('building_id'), ['building_id'], unique=True)

    op.create_table('sections',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('section_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('page_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('description', mysql.VARCHAR(length=225), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], name=op.f('sections_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('section_name'), ['section_name'], unique=True)

    op.create_table('majors',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('major_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('major_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('majors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('major_name'), ['major_name'], unique=True)
        batch_op.create_index(batch_op.f('major_id'), ['major_id'], unique=True)

    op.create_table('timetables',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('period_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('timetable_id', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], name=op.f('timetables_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], name=op.f('timetables_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('timetables_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], name=op.f('timetables_ibfk_4'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('timetables_ibfk_5'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)

    op.create_table('pages',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('page_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('page_name'), ['page_name'], unique=True)

    op.create_table('ranks',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('rank_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('rank_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('ranks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('rank_name'), ['rank_name'], unique=True)
        batch_op.create_index(batch_op.f('rank_id'), ['rank_id'], unique=True)

    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('role_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('staffs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('staff_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('staff_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('staff_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('staff_gender', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('staff_phone_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('staff_photo', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('rank_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('stype_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('staffs_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], name=op.f('staffs_ibfk_4'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('staffs_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stype_id'], ['stafftypes.id'], name=op.f('staffs_ibfk_5'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('staff_phone_number'), ['staff_phone_number'], unique=True)
        batch_op.create_index(batch_op.f('staff_id'), ['staff_id'], unique=True)
        batch_op.create_index(batch_op.f('staff_email'), ['staff_email'], unique=True)

    op.create_table('labels',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('label_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('section_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], name=op.f('labels_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('labels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('label_name'), ['label_name'], unique=True)

    op.create_table('rooms',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('room_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('room_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('building_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('roomtype_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('room_no', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], name=op.f('rooms_ibfk_1'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('rooms_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['roomtype_id'], ['roomtypes.id'], name=op.f('rooms_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('rooms_ibfk_4'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('room_no'), ['room_no'], unique=True)
        batch_op.create_index(batch_op.f('room_name'), ['room_name'], unique=True)
        batch_op.create_index(batch_op.f('room_id'), ['room_id'], unique=True)

    op.create_table('students',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('student_rno', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('student_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('student_email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('student_phone_number', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('major_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('student_photo', mysql.VARCHAR(length=225), nullable=True),
    sa.Column('student_gender', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], name=op.f('students_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('students_ibfk_3'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('student_rno'), ['student_rno'], unique=True)
        batch_op.create_index(batch_op.f('student_phone_number'), ['student_phone_number'], unique=True)
        batch_op.create_index(batch_op.f('student_email'), ['student_email'], unique=True)

    op.create_table('days',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('day_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('day_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('days', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('day_name'), ['day_name'], unique=True)
        batch_op.create_index(batch_op.f('day_id'), ['day_id'], unique=True)

    # ### end Alembic commands ###
