"""change student_photo column attribute nullabe and add default

Revision ID: 0c28fd281558
Revises: 6e6e9c4f705a
Create Date: 2025-10-17 16:17:11.355565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0c28fd281558'
down_revision = '6e6e9c4f705a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_photo',
               existing_type=mysql.VARCHAR(length=225),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('student_photo',
               existing_type=mysql.VARCHAR(length=225),
               nullable=False)

    # ### end Alembic commands ###
