"""empty message

Revision ID: 10b7540aab5c
Revises: c91246d88369
Create Date: 2026-05-17 23:37:13.874181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10b7540aab5c'
down_revision = 'c91246d88369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_student', sa.Integer(), nullable=False),
    sa.Column('total_staff', sa.Integer(), nullable=False),
    sa.Column('graduated_student', sa.Integer(), nullable=False),
    sa.Column('current_student', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=225),
               nullable=True)
        batch_op.alter_column('filepath',
               existing_type=mysql.VARCHAR(length=225),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('filepath',
               existing_type=mysql.VARCHAR(length=225),
               nullable=False)
        batch_op.alter_column('filename',
               existing_type=mysql.VARCHAR(length=225),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    op.drop_table('counts')
    # ### end Alembic commands ###
