"""update semesters

Revision ID: 137dedf95e34
Revises: 29ff88b84e2f
Create Date: 2025-10-24 21:02:58.043846

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '137dedf95e34'
down_revision = '29ff88b84e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('semester_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('semester_term', sa.String(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('semesters_id'))
        batch_op.drop_index(batch_op.f('semesters_name'))
        batch_op.drop_index(batch_op.f('semesters_term'))
        batch_op.create_unique_constraint(None, ['semester_term'])
        batch_op.create_unique_constraint(None, ['semester_name'])
        batch_op.create_unique_constraint(None, ['semester_id'])
        batch_op.drop_column('semesters_term')
        batch_op.drop_column('semesters_name')
        batch_op.drop_column('semesters_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semesters_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('semesters_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('semesters_term', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('semesters_term'), ['semesters_term'], unique=True)
        batch_op.create_index(batch_op.f('semesters_name'), ['semesters_name'], unique=True)
        batch_op.create_index(batch_op.f('semesters_id'), ['semesters_id'], unique=True)
        batch_op.drop_column('semester_term')
        batch_op.drop_column('semester_name')
        batch_op.drop_column('semester_id')

    # ### end Alembic commands ###
