"""remove a column named student_id from students table

Revision ID: 13874bdf9294
Revises: 539bfbc0763c
Create Date: 2025-10-15 19:09:45.865722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13874bdf9294'
down_revision = '539bfbc0763c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('student_id'))
        batch_op.drop_column('student_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('student_id'), ['student_id'], unique=True)

    # ### end Alembic commands ###
