"""upgrade courses table

Revision ID: 22a9fa16b649
Revises: 5928bea925fb
Create Date: 2025-10-31 14:32:43.243955

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '22a9fa16b649'
down_revision = '5928bea925fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('course_name'))
        batch_op.drop_column('course_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('course_name'), ['course_name'], unique=True)

    # ### end Alembic commands ###
