"""update staffs table

Revision ID: 242daabdbf6b
Revises: 32314df6e439
Create Date: 2025-11-11 09:23:49.911155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '242daabdbf6b'
down_revision = '32314df6e439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roomtypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roomtype_id', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roomtype_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roomtypes')
    # ### end Alembic commands ###
