"""empty message

Revision ID: 283aecb79166
Revises: 7191aea41922
Create Date: 2026-06-11 10:46:29.302275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283aecb79166'
down_revision = '7191aea41922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collabroations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collabroations')
    # ### end Alembic commands ###
