"""update semesters

Revision ID: 29ff88b84e2f
Revises: 98290d6ffb0d
Create Date: 2025-10-24 20:48:07.295026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ff88b84e2f'
down_revision = '98290d6ffb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semesters_term', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['semesters_term'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('semesters_term')

    # ### end Alembic commands ###
