"""update stafftypes table

Revision ID: 30637efc19c6
Revises: 242daabdbf6b
Create Date: 2025-11-11 09:27:59.159144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30637efc19c6'
down_revision = '242daabdbf6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('staffs_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('type_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('staffs_ibfk_2'), 'stypes', ['type_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
