"""add table staffs

Revision ID: 30aba8dfc0df
Revises: 49290e33778e
Create Date: 2025-10-17 23:23:17.817395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30aba8dfc0df'
down_revision = '49290e33778e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('staff_id', sa.String(length=100), nullable=False),
    sa.Column('staff_name', sa.String(length=100), nullable=False),
    sa.Column('staff_class', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_class'),
    sa.UniqueConstraint('staff_id'),
    sa.UniqueConstraint('staff_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffs')
    # ### end Alembic commands ###
