"""empty message

Revision ID: 3126040e2c45
Revises: fa806b90bd11
Create Date: 2026-06-04 10:58:06.610659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3126040e2c45'
down_revision = 'fa806b90bd11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
