"""update periods table

Revision ID: 32314df6e439
Revises: a7e45b988bb6
Create Date: 2025-11-10 16:09:56.181702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32314df6e439'
down_revision = 'a7e45b988bb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('period_start', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('period_end', sa.Time(), nullable=False))
        batch_op.create_unique_constraint(None, ['period_end'])
        batch_op.create_unique_constraint(None, ['period_start'])

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timetable_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.drop_column('timetable_id')

    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('period_end')
        batch_op.drop_column('period_start')

    # ### end Alembic commands ###
