"""empty message

Revision ID: 37e5ba76a75e
Revises: 444424697bae
Create Date: 2026-05-16 06:03:08.068755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '37e5ba76a75e'
down_revision = '444424697bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lab_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lab_type', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('lab_name')
    )
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratory_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'laboratories', ['laboratory_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.drop_column('is_laboratory')
        batch_op.drop_column('is_publications')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_photo', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_photo')

    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_publications', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('is_laboratory', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('laboratory_id')

    op.drop_table('laboratories')
    # ### end Alembic commands ###
