"""empty message

Revision ID: 39643c40b13e
Revises: 7a4a2a9d2d14
Create Date: 2026-05-16 19:11:35.654514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '39643c40b13e'
down_revision = '7a4a2a9d2d14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_type', sa.String(length=50), nullable=False))
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', mysql.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('media_type')

    # ### end Alembic commands ###
