"""empty message

Revision ID: 444424697bae
Revises: 980676507500
Create Date: 2026-05-15 14:54:53.630334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '444424697bae'
down_revision = '980676507500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder', sa.String(length=400), nullable=False))
        batch_op.drop_index(batch_op.f('filepath'))
        batch_op.create_unique_constraint(None, ['folder'])
        batch_op.drop_column('filepath')

    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_publications', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('is_laboratory', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.drop_column('is_laboratory')
        batch_op.drop_column('is_publications')

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', mysql.VARCHAR(length=400), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('filepath'), ['filepath'], unique=True)
        batch_op.drop_column('folder')

    # ### end Alembic commands ###
