"""empty message

Revision ID: 4672b624ae2d
Revises: ef647a6dd1e3
Create Date: 2026-05-11 00:55:12.421774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4672b624ae2d'
down_revision = 'ef647a6dd1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('text_description',
               existing_type=mysql.VARCHAR(length=400),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('text_description',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###
