"""update department

Revision ID: 481699ecc31f
Revises: c981562cebc6
Create Date: 2025-10-22 19:17:09.042457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '481699ecc31f'
down_revision = 'c981562cebc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_game', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['department_game'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('department_game')

    # ### end Alembic commands ###
