"""drop table teachers

Revision ID: 49290e33778e
Revises: 4d529a37c21d
Create Date: 2025-10-17 23:21:56.030184

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49290e33778e'
down_revision = '4d529a37c21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('teacher_class'))
        batch_op.drop_index(batch_op.f('teacher_id'))
        batch_op.drop_index(batch_op.f('teacher_name'))

    op.drop_table('teachers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('teacher_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('teacher_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('teacher_class', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('department_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], name=op.f('teachers_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('teacher_name'), ['teacher_name'], unique=True)
        batch_op.create_index(batch_op.f('teacher_id'), ['teacher_id'], unique=True)
        batch_op.create_index(batch_op.f('teacher_class'), ['teacher_class'], unique=True)

    # ### end Alembic commands ###
