"""empty message

Revision ID: 4bab8f893fcb
Revises: 4672b624ae2d
Create Date: 2026-05-12 14:59:05.761685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bab8f893fcb'
down_revision = '4672b624ae2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=225), nullable=False),
    sa.Column('filepath', sa.String(length=225), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_name'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filepath')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('attendance_id'))

    op.drop_table('attendances')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendances',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('attendance_id', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('attendance_id'), ['attendance_id'], unique=True)

    op.drop_table('activities')
    # ### end Alembic commands ###
