"""add column named staff_type

Revision ID: 4c1955b9ddf3
Revises: 86ed07cb205c
Create Date: 2025-10-18 08:09:26.275507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c1955b9ddf3'
down_revision = '86ed07cb205c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_type', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.drop_column('staff_type')

    # ### end Alembic commands ###
