"""remove column named teacher_id

Revision ID: 4d529a37c21d
Revises: a070762299b8
Create Date: 2025-10-17 23:20:31.609242

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d529a37c21d'
down_revision = 'a070762299b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('courses_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('courses_ibfk_3'), 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
