"""update subjects

Revision ID: 4f28b8c8846e
Revises: 7048f2fc9df4
Create Date: 2025-10-24 10:54:31.450366

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4f28b8c8846e'
down_revision = '7048f2fc9df4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subjects_ibfk_3'), type_='foreignkey')
        batch_op.drop_column('semester_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('subjects_ibfk_3'), 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
