"""update rooms table

Revision ID: 5c74fae98f21
Revises: 112fc6080412
Create Date: 2025-11-12 10:36:51.079306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c74fae98f21'
down_revision = '112fc6080412'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('semester_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'semesters', ['semester_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('semester_id')
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
