"""Changed user_password unique constraint to False

Revision ID: 64ef36be5433
Revises: a781cea676e3
Create Date: 2025-10-15 08:58:02.349929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64ef36be5433'
down_revision = 'a781cea676e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('user_password'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('user_password'), ['user_password'], unique=True)

    # ### end Alembic commands ###
