"""empty message

Revision ID: 6689ccd02c34
Revises: 0a9f77c71987
Create Date: 2026-05-15 12:34:47.814486

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6689ccd02c34'
down_revision = '0a9f77c71987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('department_id'))
        batch_op.drop_column('department_id')

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('semester_id'))
        batch_op.drop_column('semester_id')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_column('subject_id')

    with op.batch_alter_table('years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('year_id'))
        batch_op.drop_column('year_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('years', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('year_id'), ['year_id'], unique=True)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_id', mysql.VARCHAR(length=100), nullable=False))

    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('semester_id'), ['semester_id'], unique=True)

    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('department_id'), ['department_id'], unique=True)

    # ### end Alembic commands ###
