"""empty message

Revision ID: 66a944f06eb4
Revises: b8da7ac148a5
Create Date: 2026-05-16 20:13:22.378773

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66a944f06eb4'
down_revision = 'b8da7ac148a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('filename'))
        batch_op.drop_index(batch_op.f('folder'))

    op.drop_table('medias')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medias',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('activity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('research_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('folder', mysql.VARCHAR(length=400), nullable=False),
    sa.Column('laboratory_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('media_type', mysql.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('medias_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['laboratory_id'], ['laboratories.id'], name=op.f('medias_ibfk_3'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['research_id'], ['researches.id'], name=op.f('medias_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('folder'), ['folder'], unique=True)
        batch_op.create_index(batch_op.f('filename'), ['filename'], unique=True)

    # ### end Alembic commands ###
