"""drop times table and create periods table

Revision ID: 6b90dc1193fc
Revises: d7f28975daa1
Create Date: 2025-11-10 09:42:26.393031

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b90dc1193fc'
down_revision = 'd7f28975daa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('period_id', sa.String(length=100), nullable=False),
    sa.Column('period_start', sa.String(length=100), nullable=False),
    sa.Column('period_end', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('period_end'),
    sa.UniqueConstraint('period_id'),
    sa.UniqueConstraint('period_start')
    )
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('end_time'))
        batch_op.drop_index(batch_op.f('start_time'))
        batch_op.drop_index(batch_op.f('time_id'))

    op.drop_table('times')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('times',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('time_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_time', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('end_time', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('times', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('time_id'), ['time_id'], unique=True)
        batch_op.create_index(batch_op.f('start_time'), ['start_time'], unique=True)
        batch_op.create_index(batch_op.f('end_time'), ['end_time'], unique=True)

    op.drop_table('periods')
    # ### end Alembic commands ###
