"""remove column named course_id from subjects

Revision ID: 6e6e9c4f705a
Revises: d789235dc10b
Create Date: 2025-10-17 14:31:43.819434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e6e9c4f705a'
down_revision = 'd789235dc10b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subjects_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('subjects_ibfk_2'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
