"""update subjects

Revision ID: 7048f2fc9df4
Revises: ea671b4d40bd
Create Date: 2025-10-24 09:23:59.774766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7048f2fc9df4'
down_revision = 'ea671b4d40bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_code', sa.String(length=200), nullable=False))
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
        batch_op.create_unique_constraint(None, ['subject_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('description',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('subject_code')

    # ### end Alembic commands ###
