"""empty message

Revision ID: 7191aea41922
Revises: 969ce38a0fdb
Create Date: 2026-06-11 10:24:00.410336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7191aea41922'
down_revision = '969ce38a0fdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vision_missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vision', sa.String(length=200), nullable=False),
    sa.Column('mission', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vision_missions')
    # ### end Alembic commands ###
