"""add a column named student_photo on students table

Revision ID: 74535a540fb2
Revises: 13874bdf9294
Create Date: 2025-10-15 21:52:10.752967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74535a540fb2'
down_revision = '13874bdf9294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_photo', sa.String(length=225), nullable=False))
        batch_op.drop_index(batch_op.f('student_name'))
        batch_op.create_unique_constraint(None, ['student_photo'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('student_name'), ['student_name'], unique=True)
        batch_op.drop_column('student_photo')

    # ### end Alembic commands ###
