"""update department

Revision ID: 75cd7ab51878
Revises: 481699ecc31f
Create Date: 2025-10-22 19:18:20.375893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75cd7ab51878'
down_revision = '481699ecc31f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('department_game'))
        batch_op.drop_column('department_game')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_game', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_index(batch_op.f('department_game'), ['department_game'], unique=True)

    # ### end Alembic commands ###
