"""empty message

Revision ID: 77665b46a7ce
Revises: 9526c1aff394
Create Date: 2026-05-16 16:04:38.538104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '77665b46a7ce'
down_revision = '9526c1aff394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_avatar', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
