"""add a column named student_gender on students table

Revision ID: 78c03b14b59c
Revises: 74535a540fb2
Create Date: 2025-10-16 08:02:49.033202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c03b14b59c'
down_revision = '74535a540fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_gender', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('student_gender')

    # ### end Alembic commands ###
