"""empty message

Revision ID: 7a4a2a9d2d14
Revises: 3f93485a9b35
Create Date: 2026-05-16 19:03:06.199018

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7a4a2a9d2d14'
down_revision = '3f93485a9b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratory_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('laboratory_type', sa.String(length=100), nullable=False))
        batch_op.drop_index(batch_op.f('lab_name'))
        batch_op.create_unique_constraint(None, ['laboratory_name'])
        batch_op.drop_column('lab_type')
        batch_op.drop_column('lab_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lab_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('lab_type', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('lab_name'), ['lab_name'], unique=True)
        batch_op.drop_column('laboratory_type')
        batch_op.drop_column('laboratory_name')

    # ### end Alembic commands ###
