"""empty message

Revision ID: 86ed07cb205c
Revises: babcbfeb06c3
Create Date: 2025-10-17 23:28:09.771272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '86ed07cb205c'
down_revision = 'babcbfeb06c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_email', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('staff_gender', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('staff_phone_number', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('staff_photo', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('staff_role', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('staff_rank', sa.String(length=100), nullable=False))
        batch_op.alter_column('department_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_index(batch_op.f('staff_class'))
        batch_op.drop_index(batch_op.f('staff_name'))
        batch_op.create_unique_constraint(None, ['staff_email'])
        batch_op.create_unique_constraint(None, ['staff_phone_number'])
        batch_op.drop_column('staff_class')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_class', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('staff_name'), ['staff_name'], unique=True)
        batch_op.create_index(batch_op.f('staff_class'), ['staff_class'], unique=True)
        batch_op.alter_column('department_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('staff_rank')
        batch_op.drop_column('staff_role')
        batch_op.drop_column('staff_photo')
        batch_op.drop_column('staff_phone_number')
        batch_op.drop_column('staff_gender')
        batch_op.drop_column('staff_email')

    # ### end Alembic commands ###
