"""empty message

Revision ID: 9526c1aff394
Revises: 37e5ba76a75e
Create Date: 2026-05-16 13:06:53.033023

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9526c1aff394'
down_revision = '37e5ba76a75e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=50), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_avatar', sa.String(length=255), nullable=False))
        batch_op.drop_column('user_photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_photo', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('user_avatar')

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###
