"""empty message

Revision ID: 980676507500
Revises: 6689ccd02c34
Create Date: 2026-05-15 12:53:42.637655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '980676507500'
down_revision = '6689ccd02c34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('research_name')
    )
    with op.batch_alter_table('researchs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('category'))
        batch_op.drop_index(batch_op.f('description'))
        batch_op.drop_index(batch_op.f('filename'))
        batch_op.drop_index(batch_op.f('filepath'))
        batch_op.drop_index(batch_op.f('research_name'))

    op.drop_table('researchs')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('filename'))
        batch_op.drop_index(batch_op.f('filepath'))
        batch_op.drop_column('filename')
        batch_op.drop_column('filepath')

    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('research_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'researches', ['research_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'activities', ['activity_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('research_id')
        batch_op.drop_column('activity_id')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filepath', mysql.VARCHAR(length=225), nullable=False))
        batch_op.add_column(sa.Column('filename', mysql.VARCHAR(length=225), nullable=False))
        batch_op.create_index(batch_op.f('filepath'), ['filepath'], unique=True)
        batch_op.create_index(batch_op.f('filename'), ['filename'], unique=True)

    op.create_table('researchs',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('research_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('category', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=False),
    sa.Column('filename', mysql.VARCHAR(length=225), nullable=False),
    sa.Column('filepath', mysql.VARCHAR(length=225), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('researchs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('research_name'), ['research_name'], unique=True)
        batch_op.create_index(batch_op.f('filepath'), ['filepath'], unique=True)
        batch_op.create_index(batch_op.f('filename'), ['filename'], unique=True)
        batch_op.create_index(batch_op.f('description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('category'), ['category'], unique=True)

    op.drop_table('researches')
    # ### end Alembic commands ###
