"""update subjects

Revision ID: 98290d6ffb0d
Revises: 9b9c98bcbc6a
Create Date: 2025-10-24 15:06:24.106833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98290d6ffb0d'
down_revision = '9b9c98bcbc6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_id', sa.String(length=100), nullable=False),
    sa.Column('year_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_id'),
    sa.UniqueConstraint('year_name')
    )
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'years', ['year_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('year_id')

    op.drop_table('years')
    # ### end Alembic commands ###
