"""update subjects

Revision ID: 9b9c98bcbc6a
Revises: 4f28b8c8846e
Create Date: 2025-10-24 13:16:28.614392

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b9c98bcbc6a'
down_revision = '4f28b8c8846e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('semesters_ibfk_1'), type_='foreignkey')
        batch_op.drop_column('major_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semesters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('major_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('semesters_ibfk_1'), 'majors', ['major_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
