"""add foreign key on staffs table

Revision ID: 9f84f778d5dc
Revises: cb55eb76ce27
Create Date: 2025-11-11 09:32:38.698286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f84f778d5dc'
down_revision = 'cb55eb76ce27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stype_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stafftypes', ['stype_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stype_id')

    # ### end Alembic commands ###
