"""update column attribute from student_photo

Revision ID: a070762299b8
Revises: 0c28fd281558
Create Date: 2025-10-17 20:21:20.306452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a070762299b8'
down_revision = '0c28fd281558'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('student_photo'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('student_photo'), ['student_photo'], unique=True)

    # ### end Alembic commands ###
