"""Initial migration

Revision ID: a781cea676e3
Revises: 
Create Date: 2025-10-13 11:37:23.557142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a781cea676e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('building_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id'),
    sa.UniqueConstraint('room_name')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.String(length=100), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id'),
    sa.UniqueConstraint('subject_name')
    )
    op.create_table('teachers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.String(length=100), nullable=False),
    sa.Column('teacher_name', sa.String(length=100), nullable=False),
    sa.Column('teacher_class', sa.String(length=100), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_class'),
    sa.UniqueConstraint('teacher_id'),
    sa.UniqueConstraint('teacher_name')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('course_name', sa.String(length=100), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id'),
    sa.UniqueConstraint('course_name')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('student_rno', sa.String(length=100), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_email', sa.String(length=100), nullable=False),
    sa.Column('student_phone_number', sa.String(length=100), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_email'),
    sa.UniqueConstraint('student_id'),
    sa.UniqueConstraint('student_name'),
    sa.UniqueConstraint('student_phone_number'),
    sa.UniqueConstraint('student_rno')
    )
    op.create_table('timetable',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('major_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('time_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['major_id'], ['majors.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['time_id'], ['times.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetable')
    op.drop_table('students')
    op.drop_table('courses')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('rooms')
    # ### end Alembic commands ###
