"""update timetables table

Revision ID: a7e45b988bb6
Revises: 6b90dc1193fc
Create Date: 2025-11-10 09:46:40.805642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7e45b988bb6'
down_revision = '6b90dc1193fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('staff_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('id'))

    op.drop_table('timetable')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timetable',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('subject_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('staff_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], name=op.f('timetable_ibfk_2'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], name=op.f('timetable_ibfk_6'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['staffs.id'], name=op.f('timetable_ibfk_7'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('timetable_ibfk_4'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('id'), ['id'], unique=True)

    op.drop_table('timetables')
    # ### end Alembic commands ###
