"""update subjectmodel

Revision ID: adddb4c853e1
Revises: 137dedf95e34
Create Date: 2025-10-26 06:52:46.673119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adddb4c853e1'
down_revision = '137dedf95e34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('description'))
        batch_op.drop_index(batch_op.f('subject_code'))
        batch_op.drop_index(batch_op.f('subject_id'))
        batch_op.drop_index(batch_op.f('subject_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('subject_name'), ['subject_name'], unique=True)
        batch_op.create_index(batch_op.f('subject_id'), ['subject_id'], unique=True)
        batch_op.create_index(batch_op.f('subject_code'), ['subject_code'], unique=True)
        batch_op.create_index(batch_op.f('description'), ['description'], unique=True)

    # ### end Alembic commands ###
