"""empty message

Revision ID: b8da7ac148a5
Revises: c9ad338dae39
Create Date: 2026-05-16 20:09:02.435991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8da7ac148a5'
down_revision = 'c9ad338dae39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=225), nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.String(length=225), nullable=False))
        batch_op.create_unique_constraint(None, ['filename'])
        batch_op.create_unique_constraint(None, ['filepath'])

    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('filename', sa.String(length=225), nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.String(length=225), nullable=False))
        batch_op.drop_index(batch_op.f('laboratory_name'))
        batch_op.create_unique_constraint(None, ['research_name'])
        batch_op.create_unique_constraint(None, ['filename'])
        batch_op.create_unique_constraint(None, ['category'])
        batch_op.create_unique_constraint(None, ['filepath'])
        batch_op.drop_column('laboratory_name')

    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=225), nullable=False))
        batch_op.add_column(sa.Column('filepath', sa.String(length=225), nullable=False))
        batch_op.create_unique_constraint(None, ['filename'])
        batch_op.create_unique_constraint(None, ['filepath'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')

    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratory_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('laboratory_name'), ['laboratory_name'], unique=True)
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')
        batch_op.drop_column('research_name')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('filepath')
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
