"""empty message

Revision ID: c2dd30989fe1
Revises: 66a944f06eb4
Create Date: 2026-05-16 20:47:07.498095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2dd30989fe1'
down_revision = '66a944f06eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('activity_name'))
        batch_op.drop_index(batch_op.f('category'))
        batch_op.drop_index(batch_op.f('description'))

    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('category'))
        batch_op.drop_index(batch_op.f('description'))
        batch_op.drop_index(batch_op.f('research_name'))

    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('category'))
        batch_op.drop_index(batch_op.f('description'))
        batch_op.drop_index(batch_op.f('research_name'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('research_name'), ['research_name'], unique=True)
        batch_op.create_index(batch_op.f('description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('category'), ['category'], unique=True)

    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('research_name'), ['research_name'], unique=True)
        batch_op.create_index(batch_op.f('description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('category'), ['category'], unique=True)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('description'), ['description'], unique=True)
        batch_op.create_index(batch_op.f('category'), ['category'], unique=True)
        batch_op.create_index(batch_op.f('activity_name'), ['activity_name'], unique=True)

    # ### end Alembic commands ###
