"""empty message

Revision ID: c62e0b1561a5
Revises: d41053088383
Create Date: 2026-06-19 11:19:02.536893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c62e0b1561a5'
down_revision = 'd41053088383'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collabroations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('collaboration_type', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collabroations', schema=None) as batch_op:
        batch_op.drop_column('collaboration_type')

    # ### end Alembic commands ###
