"""empty message

Revision ID: c7f306403736
Revises: 
Create Date: 2026-06-16 12:31:19.806707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f306403736'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='Pending', nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('activity_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=225), nullable=True),
    sa.Column('filepath', sa.String(length=225), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('collabroations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('counts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('total_student', sa.Integer(), nullable=False),
    sa.Column('total_staff', sa.Integer(), nullable=False),
    sa.Column('graduated_student', sa.Integer(), nullable=False),
    sa.Column('current_student', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dashboards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('attr_key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attr_key')
    )
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('department_name')
    )
    op.create_table('laboratories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('laboratory_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=225), nullable=False),
    sa.Column('filepath', sa.String(length=225), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('researches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=225), nullable=False),
    sa.Column('filepath', sa.String(length=225), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filepath')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_installed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=150), nullable=False),
    sa.Column('user_password', sa.Text(), nullable=False),
    sa.Column('user_role', sa.String(length=50), nullable=False),
    sa.Column('user_avatar', sa.String(length=255), server_default='3d-avatar-1.avif', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('years',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year_name')
    )
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('semester_name', sa.String(length=100), nullable=False),
    sa.Column('semester_term', sa.String(length=100), nullable=False),
    sa.Column('year_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['year_id'], ['years.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('semester_name'),
    sa.UniqueConstraint('semester_term')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('subject_code', sa.String(length=200), nullable=False),
    sa.Column('subject_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision_missions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vision', sa.String(length=200), nullable=False),
    sa.Column('mission', sa.String(length=200), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.String(length=100), nullable=False),
    sa.Column('course_name', sa.String(length=200), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_semester_id'), ['semester_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_subject_id'))
        batch_op.drop_index(batch_op.f('ix_courses_semester_id'))

    op.drop_table('courses')
    op.drop_table('vision_missions')
    op.drop_table('subjects')
    op.drop_table('semesters')
    op.drop_table('years')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('researches')
    op.drop_table('laboratories')
    op.drop_table('departments')
    op.drop_table('dashboards')
    op.drop_table('counts')
    op.drop_table('collabroations')
    op.drop_table('activities')
    op.drop_table('academic_calendars')
    # ### end Alembic commands ###
