"""empty message

Revision ID: c91246d88369
Revises: c2dd30989fe1
Create Date: 2026-05-16 21:52:14.362327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c91246d88369'
down_revision = 'c2dd30989fe1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratory_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('research_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('research_name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('laboratory_name')

    # ### end Alembic commands ###
