"""add new tables

Revision ID: c981562cebc6
Revises: 4c1955b9ddf3
Create Date: 2025-10-18 12:29:55.965688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c981562cebc6'
down_revision = '4c1955b9ddf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rank_id', sa.String(length=100), nullable=False),
    sa.Column('rank_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rank_id'),
    sa.UniqueConstraint('rank_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_id', sa.String(length=100), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('stypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stype_id', sa.String(length=100), nullable=False),
    sa.Column('stype_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stype_id'),
    sa.UniqueConstraint('stype_name')
    )
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rank_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'stypes', ['type_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'roles', ['role_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'ranks', ['rank_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('staff_type')
        batch_op.drop_column('staff_rank')
        batch_op.drop_column('staff_role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_role', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('staff_rank', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('staff_type', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('type_id')
        batch_op.drop_column('rank_id')
        batch_op.drop_column('role_id')

    op.drop_table('stypes')
    op.drop_table('roles')
    op.drop_table('ranks')
    # ### end Alembic commands ###
