"""empty message

Revision ID: c9ad338dae39
Revises: 39643c40b13e
Create Date: 2026-05-16 19:13:17.459587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9ad338dae39'
down_revision = '39643c40b13e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.drop_column('laboratory_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laboratories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratory_type', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
