"""empty message

Revision ID: ca8bf0bfc526
Revises: ab1db2792673
Create Date: 2026-06-12 12:33:11.643248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8bf0bfc526'
down_revision = 'ab1db2792673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
