"""add stafftypes table

Revision ID: cb55eb76ce27
Revises: 30637efc19c6
Create Date: 2025-11-11 09:29:09.645384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb55eb76ce27'
down_revision = '30637efc19c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stafftypes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stype_id', sa.String(length=100), nullable=False),
    sa.Column('stype_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stype_id'),
    sa.UniqueConstraint('stype_name')
    )
    with op.batch_alter_table('stypes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('stype_id'))
        batch_op.drop_index(batch_op.f('stype_name'))

    op.drop_table('stypes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stypes',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('stype_id', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('stype_name', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('stypes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('stype_name'), ['stype_name'], unique=True)
        batch_op.create_index(batch_op.f('stype_id'), ['stype_id'], unique=True)

    op.drop_table('stafftypes')
    # ### end Alembic commands ###
