"""empty message

Revision ID: d41053088383
Revises: c7f306403736
Create Date: 2026-06-19 11:15:43.803060

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd41053088383'
down_revision = 'c7f306403736'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collabroations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organization_name', sa.String(length=200), nullable=False))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collabroations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('organization_name')

    # ### end Alembic commands ###
