"""remove foreign key from timetable

Revision ID: d7f28975daa1
Revises: 07aae37a9073
Create Date: 2025-11-10 09:39:53.952372

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7f28975daa1'
down_revision = '07aae37a9073'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('timetable_ibfk_5'), type_='foreignkey')
        batch_op.drop_column('time_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('timetable_ibfk_5'), 'times', ['time_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
