"""empty message

Revision ID: e18f073dc23d
Revises: 4bab8f893fcb
Create Date: 2026-05-12 16:13:48.795841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e18f073dc23d'
down_revision = '4bab8f893fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('researchs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('filename', sa.String(length=225), nullable=False),
    sa.Column('filepath', sa.String(length=225), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('filepath'),
    sa.UniqueConstraint('research_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('researchs')
    # ### end Alembic commands ###
