"""update roomtype table

Revision ID: e47adc168e2f
Revises: c0abfb4bbe43
Create Date: 2025-11-11 19:33:15.603887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e47adc168e2f'
down_revision = 'c0abfb4bbe43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomtypes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roomtype_name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['roomtype_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roomtypes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('roomtype_name')

    # ### end Alembic commands ###
