"""update course Model

Revision ID: e9b34e3fd586
Revises: 22a9fa16b649
Create Date: 2025-11-09 07:55:17.580543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b34e3fd586'
down_revision = '22a9fa16b649'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('course_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('course_id'), ['course_id'], unique=True)

    # ### end Alembic commands ###
