"""empty message

Revision ID: ef647a6dd1e3
Revises: 7b5f955bfb4f
Create Date: 2026-05-10 12:35:25.482862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef647a6dd1e3'
down_revision = '7b5f955bfb4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=225), nullable=True))

    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('text_description',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=400),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('texts', schema=None) as batch_op:
        batch_op.alter_column('text_description',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
