"""empty message

Revision ID: f28f999e8d3d
Revises: e35de20e5dbe
Create Date: 2026-06-03 11:05:17.435576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f28f999e8d3d'
down_revision = 'e35de20e5dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_calendars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=100), nullable=True))
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_calendars', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('title')

    # ### end Alembic commands ###
