"""empty message

Revision ID: fbe8d34d84a0
Revises: d7ee490b996a
Create Date: 2026-05-13 06:53:26.440618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbe8d34d84a0'
down_revision = 'd7ee490b996a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researchs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['category'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('researchs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
